# Generated by Django 4.2.14 on 2024-07-25 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('main_body', models.TextField()),
                ('post_created_on', models.DateTimeField(auto_now_add=True)),
                ('post_updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('difficulty', models.IntegerField(choices=[(0, 'All Levels'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=0)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyexam_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
