# Generated by Django 4.2.14 on 2024-07-25 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyexamtips', '0005_post_favourites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(0, 'No Category'), (1, 'Study Tips'), (2, 'Exam Tips')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='user_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
