# Generated by Django 4.2.14 on 2024-07-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyexamtips', '0009_remove_post_favourites_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
