# Generated by Django 4.2.14 on 2024-08-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyexamtips', '0011_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
