# Generated by Django 4.2.14 on 2024-08-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyexamtips', '0012_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
    ]
